//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookRegistrationEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int CustomerID { get; set; }
        public string ISBN { get; set; }
        public System.DateTime RegDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
